services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=ms-gerenciamento-pedidos'
      - 'POSTGRES_PASSWORD=admin'